[package]
name = "open62541-sys"
version = "0.1.0"
authors = ["Andreas Walter <andreas.walter@waltronix.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1.42"
bindgen = "0.58.1"
